apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-jupyter-workarea
spec:
  title: "Jupyter Workarea"
  description: Demonstration of providing a workarea for using Jupyter.
  workshop:
    image: conda-environment:*
    files:
    - image:
        url: $(image_repository)/lab-jupyter-workarea-files:latest
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    resources:
      memory: 2Gi
      storage: 5Gi
    namespaces:
      budget: medium
    applications:
      workshop:
        enabled: false
      terminal:
        enabled: false
    env:
    - name: ENABLE_JUPYTERLAB
      value: "true"
    ingresses:
    - name: jupyter
      port: 8888
    dashboards:
    - name: Jupyter
      url: "$(ingress_protocol)://jupyter-$(session_namespace).$(ingress_domain)/"
